// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project4_1.Models;

namespace Project4_1.Migrations
{
    [DbContext(typeof(ContactDbContext))]
    [Migration("20220415195046_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Project4_1.Models.ContactModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("categoryID")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("organization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            categoryID = 3,
                            email = "mark.smith@yahoo.com",
                            firstName = "Mark",
                            lastName = "Smith",
                            phone = "440-505-3513"
                        },
                        new
                        {
                            ID = 2,
                            categoryID = 5,
                            email = "lj1989@gmail.com",
                            firstName = "Linda",
                            lastName = "Jones",
                            phone = "638-424-2940"
                        },
                        new
                        {
                            ID = 3,
                            categoryID = 2,
                            email = "bailey.stewart@aol.com",
                            firstName = "Bailey",
                            lastName = "Stewart",
                            organization = "Apple",
                            phone = "034-514-5462"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
