// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project4_1.Models;

namespace Project4_1.Migrations
{
    [DbContext(typeof(ContactDbContext))]
    partial class ContactDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Project4_1.Models.Category", b =>
                {
                    b.Property<string>("categoryID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("categoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            categoryID = "1",
                            name = "Work"
                        },
                        new
                        {
                            categoryID = "2",
                            name = "Family"
                        },
                        new
                        {
                            categoryID = "3",
                            name = "Friend"
                        },
                        new
                        {
                            categoryID = "4",
                            name = "Personal"
                        },
                        new
                        {
                            categoryID = "5",
                            name = "Other"
                        });
                });

            modelBuilder.Entity("Project4_1.Models.ContactModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("categoryID1")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("organization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("categoryID1");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            email = "mark.smith@yahoo.com",
                            firstName = "Mark",
                            lastName = "Smith",
                            phone = "440-505-3513"
                        },
                        new
                        {
                            ID = 2,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            email = "lj1989@gmail.com",
                            firstName = "Linda",
                            lastName = "Jones",
                            phone = "638-424-2940"
                        },
                        new
                        {
                            ID = 3,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            email = "bailey.stewart@aol.com",
                            firstName = "Bailey",
                            lastName = "Stewart",
                            organization = "Apple",
                            phone = "034-514-5462"
                        });
                });

            modelBuilder.Entity("Project4_1.Models.ContactModel", b =>
                {
                    b.HasOne("Project4_1.Models.Category", "category")
                        .WithMany()
                        .HasForeignKey("categoryID1");

                    b.Navigation("category");
                });
#pragma warning restore 612, 618
        }
    }
}
